### ISSUE TITLE
Frigate Config Camera Path

### ISSUE THREAD

**Issue by conniely04** [glossyio/traffic-monitor#1]
In the Frigate Config File, the hostname for the camera path is not being generated through the shell script. The raspberry pi's hostname would need to be manually entered in order to connect the camera to Frigate. The path that is generated is: rtsp://:8554/picam_h264.

1. After cloning the Github and running Frigate, go to the Frigate Config File
2. Scroll down to the cameras configuration (Line 22). 
3. See the camera path as : rtsp://:8554/picam_h264 (Camera does not connect) 

Expected Behavior: 
The expected behavior was the camera path to be given as: EX: rtsp://192.168.7.134:8554/picam_h264. This is expected in order to have a successful camera connection to Frigate. The path that was generated that led to an unsuccessful camera connection is: rtsp://:8554/picam_h264.

Raspberry Pi Details:
 - Pi version: RPi5/4GB
 - OS: Debian GNU/Linux
 - Software Version: 12

**Comment by glossyio** [comment]
Thanks for calling this out.  The `export` command needed to be assigned the system variable `$HOSTNAME`; i.e. I needed to have `export HOSTNAME=$HOSTNAME`.
